version: '3'
services:
  postgres:
    image: arm64v8/postgres:15.3
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./.env

volumes:
  postgres-db:
