"""updated dish model

Revision ID: e2a3ab1aee13
Revises: 3995692bfb85
Create Date: 2023-06-21 16:32:38.187635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2a3ab1aee13"
down_revision = "3995692bfb85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dish",
        sa.Column("customizable_dish", sa.Boolean(), nullable=False, server_default="False"),
    )
    op.drop_column("dish", "menuEdit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dish", sa.Column("menuEdit", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("dish", "customizable_dish")
    # ### end Alembic commands ###
